---
title: "Does Ethnicity Influence Beer Consumption and Brand Choice?"
subtitle: ""
author: "Matthew Aaron Looney"
date: "May 08, 2018"

output:
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: no
    toc_depth: 4
  html_document:
    toc: yes
    toc_depth: '4'
    
abstract: "The beer industry in the United States represents more than $350 billion dollars of total economic impact. This makes the industry one of the largest consumer product sectors in America. As a category of consumer goods, beer is one of the most dynamically changing products in the country. The industry responds quickly to changes in consumer preferences and shifting consumer demographics. The continued ability to understand and predict shifts in consumer demand is paramount to the industries' ability to continue to innovate and selectively appeal to the heterogeneous consumer. It is well known that consumer demographics play a key role in determining consumer preference. A recent study by Lopez and Matschke [-@Lopez:2012ei] examine consumer preference for beer using market level data. The authors assume a heterogeneous agent model with age and income variation across consumers. Consistent with expectations, they find a strong relationship between increased age and income and lower sensitivity to price. However, the study omits other relevant consumer demographic variables, such as ethnicity. This study seeks to understand more deeply how additional consumer characteristics influence preference for beer, in particular, how ethnicity influences beer consumption and brand choice. The methodological approach taken in this study is to estimate a differentiated demand for beer using a random coefficients discrete choice model. Information Resources, Inc. (IRI) brand level data will be used as well as consumer level demographic data from the Current Population Survey (CPS)."
    
header-includes:
- \usepackage{graphicx}
- \usepackage{rotating}
- \usepackage{longtable}
- \usepackage{amssymb,amsmath}
- \usepackage{dcolumn}
- \usepackage{setspace}
- \usepackage{mathrsfs}
- \usepackage{eso-pic,graphicx,transparent}

bibliography: differentiated_Beer_Demand.bib
csl: computational-economics.csl
link-citations: true
fontsize: 12pt
geometry: margin = 1.25in

---

<!-- \AddToShipoutPictureFG{ -->
<!--   \AtPageCenter{% or \AtTextCenter -->
<!--     \makebox[0pt]{\rotatebox[origin=c]{45}{% -->
<!--       \scalebox{5}{\texttransparent{0.05}{DRAFT}}% -->
<!--     }} -->
<!--   } -->
<!-- } -->

\newpage

---

# Introduction

\doublespacing

\qquad One of the largest consumer product sectors in America is the beer industry. As a whole, this industry represents more than $350 billion dollars of total economic impact ^[Based on data from 2016 in a study by John Dunham & Associates.]. As a category of consumer goods, beer is one of the most dynamically changing products in the country. The industry responds quickly to changes in consumer preference and shifting consumer demographics. The ability of the beer industry to change quickly to appeal to a new consumer group makes the industry an interesting candidate to study with regard to changing ethnic diversity. The focus of this study is to evaluate how shifts in the consumer demographic landscape is changing how the beer industry responds to increasing populations of Hispanics and Asians. To understand this question it is important to model demand with consideration of, not only income, age, and family size, but also ethnic makeup. Ethnicity has largely been ignored in the differentiate product demand literature and this study aims to fill this gap.

\qquad According to a study by the Pew Research Center, by the year 2055 the United States will no longer have a single racial or ethnic majority [@cohn201610]. In 1965, 84% of Americans were non-Hispanic Whites, 11% Black, 4% Hispanic, less than 1% Asian and less than 1% other. By the year 2015 the ethnic distribution of the United States had shifted with non-Hispanic whites now representing 62% of the U.S. population, 12% Black, 18% Hispanic, 6% Asian and 2% other.^[Whites, Blacks and Asians include only single-race non-Hispanics. Asians include Pacific Islanders. Hispanics are of any race. Source: Pew research Center estimates based on adjusted census data] Over a 50 year period the American demographic landscape had changed with large increases in Hispanic and Asian representation. These divergent trends are expected to continue long into the future, at variable rates, depending on how immigration policy morphs with fluctuations in the political landscape [@passel2015modern].
  
\qquad When discussing ethnic trends it has become important to distinguish ethnicity from race and to define these terms precisely. Unfortunately this is not a trivial task. The classic definitions of race and ethnicity used by sociologists and anthropologist are given by the following two definitions. Race refers to a category of people who share certain inherited physical characteristics, such as skin color, facial features, and stature. Using physical differences as their criteria, scientists at one point identified as many as nine races [@Smedley:1998wf].^[African, American Indian or Native American, Asian, Australian Aborigine, European (more commonly called “white”), Indian, Melanesian, Micronesian, and Polynesian] Ethnicity refers to the shared social, cultural, and historical experiences, stemming from common national or regional backgrounds, that make subgroups of a population different from one another. Within the context of ethnicity, an ethnic group can be defined as a subgroup of a population with a set of shared social, cultural, and historical experiences; with relatively distinctive beliefs, values, and behaviors; and with some sense of identity of belonging to the subgroup [@Barkan:2016wf].  
  
\qquad There has been much debate and disagreement within the social science community when dealing with issues of race and ethnicity. However, the current general consensus is that biological definitions of race are antiquated and largely irrelevant. Issues of racial classification based on genetic profiling have muddied the waters even further.^[With the availability of DNA testing by companies such as Ancestry.com and 23andMe many people discover the true racial diversity within their genes.] With the current level of genetic diversity present in the world today it is not possible to classify an individual as purely one race over another. The idea of racial classification based on biology has dissolved and the idea of ethnic identity has emerged as the preferred method of individual demographic identifier. Due to the complexity of the problems related to using biological race as a demographic identifier I will instead use the concept of ethnicity as defined above. An increasing number of data sets are including questions about ethnicity. This self reporting of ethnic identity is fundamentally inline with the widely accepted definitions of ethnicity and thus I feel it more appropriate to use ethnic demographic information when studying consumer preference.  
  
\qquad Distinct patterns of immigration from Latin America and Asia is driving much of the current change in the demographic landscape. Hispanics and Asians are estimated to represent 70% of the total immigrant population by the year 2055 with 34% and 36%, respectively [@cohn201610]. But immigration patterns represent more than simple statistics. Immigrants are people who bring with them ethnic identity and culture. This ethnic identity is embedded in food, religion, language, and to varying degrees, permeates every aspect of an individuals identity.  The United States has always been a nation of immigrants. Since it's founding, the country has undergone three distinct episodes of immigration. The most recent between 1850 to 1930 when large waves of immigrants from Germany, Italy, Ireland, Greece and many eastern European nations landed on American soil. These immigrants changed the American food scene by bringing their food preferences with them from their home countries. Given the current changes in the ethnic landscape of the United States, it is widely accepted that a fourth episode of immigration is underway. Consumer food preference last generation is looking very different from consumer food preference in the current generation. In fact, at the current pace of ethnic change, shifts in inter-generational food preference are becoming a reality that the U.S. food industry will need to manage to appeal to the heterogeneous consumer. Understanding how food preferences change with large populations from Latin America and Asia settling in to the fabric of the United States is an important research question for economist to tackle. Many studies incorporate consumer income and age variations when studying demand for differentiated goods but few explicitly model ethnicity as an added demographic variable. I argue that ethnicity is an important component to consider when studying consumer demand. This study seeks to understand more deeply how additional consumer characteristics influence product preference, and in particular, how ethnicity influences beer consumption and brand choice. 
  
## Literature Review  
  
\qquad The theoretical framework for projecting consumer choice onto a set of product characteristics started with work by Lancaster [-@Lancaster:1966tp]. This idea was extended further by McFadden who developed the econometric model in [-@mcfadden1973conditional]. This projection allowed for the estimation of a large number of products using a finite number of characteristics. Prior to this line of research the problem of dimensionality plagued empirical industrial organization and differentiated product demand which rendered many interesting problems intractable.  
  
\qquad While dimensionality was a large problem to overcome, price endogeneity is present in almost all supply and demand models and discrete choice modeling is no exception. If I fail to account for this endogeneity then the parameter estimates will be biased and depending on the exact model specification, inconsistent. Berry (1994) introduced an elegant method to overcome the endogeneity issue. He developed a method to estimate differentiated demand models in the presence of unobserved product characteristics by inverting the market share equation to obtain an estimate of mean utility. What the inversion technique provided was a method to linearize the market share equation which then allowed for the use of linear instrumental variables. Without this method the market share equation is highly non-linear and the use of standard linear instrumental variables will not work. Once the implied mean utility is obtained the estimation can proceed in a similar way as homogeneous goods modeling. While Berry's method does allow for the handling of endogenous prices through the use of standard linear instrumental variables his method does not address the well known problem of independence of irrelevant alternatives (IIA) thereby severely restricting the cross-price elasticity patterns.^[For detailed discussions see Domencich and McFadden (1975), Hausman and Wise (1978), [@Berry:1995ud], [@Nevo:2000vk]]  
  
\qquad The incorporation of consumer heterogeneity in discrete choice modeling of differentiated products explicitly solves the IIA problem. In a paper by Berry, Levinsohn and Pakes (BLP) [-@Berry:1995ud] have shown that individual consumer heterogeneity can be applied to a discrete choice model of differentiated goods in a tractable way to uncover consistent estimations of demand elasticities. The BLP model developed a way to break the IIA property which allowed for more realistic substitution patterns across products. The BLP model has become a popular model in differentiate product demand and has become the model of choice when investigating merger simulations. However, the results obtained from the merger simulations are going to be driven by the demand model and supply side assumptions. It is therefore imperative to consider all components that may affect the demand for a product. Most studies incorporate components of income, age, and household size while studying differentiated product demand but few studies have incorporated ethnicity. I argue that ethnicity is a missing key component in determining product choice and should be included in the demand model.
  
\qquad It is well known that consumer demographics play a key role in determining consumer preference. A search of the literature related to discrete choice modeling of differentiated goods reveal few studies that incorporate other demographic variables beyond income and age. A study by Lopez and Matschke [-@Lopez:2012ei] use a random coefficients multinomial logit model to examine consumer preference for beer using market level data. The authors assume a heterogeneous agent model with age and income variation across consumers. Consistent with expectations, they find a strong relationship between increased age and income and lower sensitivity to price. However, the authors omit other relevant consumer demographic variables, such as ethnicity. One of the few studies to incorporate an ethnic variable in a random coefficients discrete choice model was Romeo [-@Romeo:2016wx]. His results show that as the percentage of Hispanics in the population increase, the utility gained from consuming Corona decrease and turn negative when moving from 18 to 22 percent Hispanics. Romeo can not offer any clear explanation of these results but suggests that perhaps with increasing percentages of Hispanics in a market, competition from other Latin American beers are moving consumers away from Corona. With so few studies on how ethnicity impacts demand it is important to systematically study this missing demographic variable. This paper aims to fill this gap by studying how ethnicity impacts demand choice in different markets across the United States.
  
## Conceptual Framework  
  
\qquad The demand system is obtained by assuming an individual will maximize their utility by selecting a product from the choice set. The conditional indirect utility of individual $i$ selecting product $j$ in market $t$ is given by $U(x_{jt}, \xi_{jt}, p_{jt}, \zeta_{i}|\theta )$, where $x_{jt}$ is a K-dimensional (row) vector of observable product characteristics, $\xi_{jt}$ is the unobserved (by the researcher) product characteristic, $p_{jt}$ is the price of product $j$ in market $t$, $\zeta{i}$ are individual characteristics, and $\theta$ is a set of unknown parameters to be estimated.

\qquad Then indirect utility is given by the following,

\begin{equation}
{u_{ijt}} = {\alpha _i}f( \cdot ) + {\beta _i}{x_{jt}} + {\xi _{jt}} + {\varepsilon _{ijt}}
\end{equation}

where, $i=1,...,I_t$, $j=1,...,J$, $t=1,...,T$, $f(\cdot)$ is a functional form for indirect utility^[Depending on the research question the functional form can take on any one of a number of utility functions. For example, if wealth effects are thought to be important then a Cobb-Douglas functional may be appropriate, if not then quasi-linear may be chosen, see [@Petrin:2002ww]], $\alpha_i$ is individual $i$'s marginal utility gained from the parameters of the utility function, $\beta_i$ is a K-dimensional (column) vector of individual-specific taste coefficients, and $\varepsilon_{ijt}$ is a mean zero stochastic error term.

\qquad The introduction of consumer heterogeneity is done through modeling individual taste preference ($\alpha_i, \beta_i$) based on consumer characteristics, $\zeta_i$. The individual consumer characteristics consist of two parts, observed characteristics, $D_i$ and unobserved characteristics $v_i$. The observed characteristics can be obtained by either sampling from a joint parametric distribution (e.g., the Current Population Survey) or by using sample data to estimate the mean and standard deviation of the characteristics of interest from a population. For example, assume a log-normal distribution on income and take random draws using the mean and standard deviation from census data. The unobserved characteristics, $v_i$, can be generated by random sampling from a parametric distribution.

\qquad Following nomenclature used by Nevo gives the following,

\begin{equation}
\left( {\begin{array}{*{20}{c}}
  {{\alpha _i}} \\ 
  {{\beta _i}} 
\end{array}} \right) = \left( {\begin{array}{*{20}{c}}
  \alpha  \\ 
  \beta  
\end{array}} \right) + \Pi {D_i} + \Sigma {v_i},{\text{     }}{v_i} \sim P_v^*(v),{\text{    }}{{\text{D}}_i} \sim \hat P_D^*(D)
\end{equation}

where, $D_i$ is observed characteristic, $v_i$ is unobserved characteristics, $P^*_v(\cdot)$ is a parametric distribution, $\hat P^*_D(\cdot)$ is either a parametric or non-parametric distribution. $\Pi$ is a matrix of parameter estimates that measure the variation in taste characteristics across demographics and $\Sigma$ is a matrix of parameter estimates for the unobserved demographic characteristics.

\qquad For completion of the demand system I need to define the outside good. Without the outside good construction, all individuals in all markets would be purchasing all products all of the time. For the econometrician to see a change in quantities demanded with a homogeneous price increase across all products (relative to other markets), I need people moving to the margins which means I need to define the option where people can make a zero purchase. I define the mean utility gained from the outside option as $U_{i0t}$. It is important to note that the outside option is not identified in the current context.^[It is possible to identify the outside option with further restrictions and normalization, see Nevo [-@Nevo:2000vk] for a more detailed discussion.]

\qquad Combining equations (1) and (2) I obtain the expression for the conditional indirect utility,

\begin{equation}
\begin{gathered}
  {u_{ijt}} = {\delta _{jt}}({x_{jt}},{p_{jt}},{\xi _{jt}}|{\theta _1}) + {\mu _{ijt}}({x_{jt}},{p_{jt}},{v_i},{D_i}|{\theta _2}) + {\varepsilon _{ijt}}, \hfill \\
  {\delta _{jt}} = \beta {x_{jt}} - \alpha {p_{jt}} + {\xi _{jt}}, \hfill \\
  {\mu _{ijt}} = [ - {p_{jt}},{x_{jt}}](\Pi {D_i} + \Sigma {v_i}) \hfill \\ 
\end{gathered}
\end{equation}

where, $\delta_{jt}$ is the mean utility, and $\mu_{ijt}$ and $\varepsilon_{ijt}$ are the mean zero deviations from the mean utility which represent the random coefficient interactions between the observed and unobserved parts of the product characteristics and the demographics. The vectors $\theta_1$ and $\theta_2$ contain the linear and nonlinear parameters of the model with $\theta_1=(\alpha, \beta)$ and $\theta_2=(\Pi, \Sigma)$.  
  
\qquad The model parameters ($\theta_1$ and $\theta_2$) can be estimated using Hansen's generalized method of moments estimation technique [@Hansen:1982ue] and following the procedures detailed in Berry, et. al. [-@Berry:1995ud] and Nevo [-@Nevo:2000vk].
  
## Data, Methods and Procedures
  
\qquad The methodological approach taken in this study is to estimate a differentiated demand for beer using the random coefficients multinomial logit model developed by Berry, et. al. [-@Berry:1995ud] and extended by Nevo [-@Nevo:2001tr], Chidmi [-@Chidmi:2006ww], Chidmi and Lopez [-@Chidmi:2007vf], and Chidmi and Murova [-@Chidmi:2011tj]. The data required to consistently estimate the model outlined in the previous section consist of the following variables: market shares, prices, brand characteristics, and information on the distribution of consumer demographics. Unlike other papers that have studied differentiated product demand this paper will incorporate a more rich set of demographic variables to elucidate how ethnic characteristics influence brand choice. In this paper a market is defined as beer sales during 2010 in Los Angeles, California over 52 weeks at the chain/brand level. The market level sales data are obtained from Information Resource Inc. (IRI) and consist of all dollar by volume sales for a brand of beer at a specific chain during a one week period. Market shares are calculated by adding up the total gallons of beer sold, by brand, in a given market and dividing by the total potential market size. The potential market size is assumed to be the per capita consumption of beer in Los Angeles, California.^[For example, the per capita consumption of beer for consumers over the age of 21 in the state of California is given as 25.5 gallons, according to 2012 data by the Beer Institute. The 2010 census estimates the population of individuals over the age of 21 in Los Angeles as 2.6 million. For weekly data, the total potential market size is 1,297,558 gallons of beer for consumers over 21.] The product characteristics used in this study are as follows: alcohol by volume (ABV), international bitterness units (IBU), a measure of beer color, referred to as the standard reference method (SRM), calories per once, and carbohydrates per once. Indicator variables are included for the brand country of origin^[Was the brewer located in the United States, Mexico, Germany, the Netherlands, etc.] and the style of beer.^[For example, Pale Lagers & Pilsners, German Style Bocks, India Pale Ale (IPA), Wheat Beer, etc.] Consumer demographics are obtained by pooling data from the 2009, 2010, and 2011 Current Population Survey, Annual Social and Economic (ASEC) Supplement.^[Very little variation in demographics occur over any three year period. The pooling of data allows me to obtain a larger sample of individuals to minimize the error propagation during the numerical integration step in the estimation phase.] The demographic variables used are total family income, individual age, individual educational attainment, and a series of survey questions that ask the following: Are you Spanish, Hispanic, or Latino?, if yes then from where^[The respondent has a choice of five countries/regions to chose from; Mexico, Puerto Rico, Cuba, Central/South America, or other Spanish.], In what country were you born?, In what country was your mother born?, and In what country was your father born? All demographic variables are taken at the individual level with the exception of total family income.^[I assume that families pool their resources and adult individuals have equal access to total family income] All demographic variables are for individuals over the age of 21, the age at which alcohol is legally purchased and consumed in the United States.  
  
  
\qquad Price data and unobserved product characteristics will be correlated with econometric error term and cause problems with endogeneity. These problem can be overcome by specifying a set of instruments that are correlated with prices and the unobserved product characteristics but uncorrelated with the error terms. (need to define and describe the IV's used... not done yet...)  
  
  
\qquad The estimation proceeds using GMM methods to form a population moment condition which is a product of the instrumental variables and a structural error term to form a nonlinear GMM estimator. Let $Z=[z_1,...z_m]$ be a set of instruments where $E[Z^\prime\cdot\omega(\theta^*)]=0$, and $\omega$ (the error term) is a function of the model parameters and $\theta^*$ denotes the true values of the model parameters. The GMM estimate is

\begin{equation}
\hat \theta  = \mathop {\arg \min }\limits_\theta  [\omega {(\theta )^\prime }Z{A^{ - 1}}{Z^\prime }\omega (\theta )]
\end{equation}

where, $A$ is a consistent estimate of $E[Z^\prime\omega\omega^\prime Z]$. Following the procedures detailed in Berry [-@Berry:1994tp], the unobserved product characteristics error term is given by $\xi_{j}+\Delta\xi_{jt}$. The unobserved product can then be computed as a function od the data and the parameters by solving for the mean utility levels, $\delta_{\cdot t}$, that solves the implicit equations,

\begin{equation}
{s_{ \cdot t}}(x,{p_{ \cdot t}},{\delta _{ \cdot t}}|{\theta _2}) = {S_{ \cdot t}}
\end{equation}

where, $s_{\cdot t}(\cdot)$ is the market share function defined by equation (define market share function in Conceptual Framework...), and $s_{\cdot t}$ are the observed market shares. The inversion can be done either numerically (for the full model) or by using the McFadden result for the logit model which gives, $\delta_{jt}(x,p_{\cdot t}, S_{\cdot t}|\theta_2)=ln(S_{jt})-ln(S_{0t})$. The error term is now defined as $\omega_{jt}=\delta_{jt}(x,p_{\cdot t}, S_{\cdot t}|\theta_2)-(x_j\beta+\alpha p_{jt})$. As Nevo [-@Nevo:2001tr] notes, the reason is now clear for separating out the $\theta_1$ and $\theta_2$ terms, $\theta_1$ enters the error term and the GMM objective function linearly while $\theta_2$ enters nonlinearly.

\qquad The estimation algorithm computer code was developed by closely following the Matlab computer code developed by Nevo [-@Nevo:2000vk] and Chidmi and Murova [-@Chidmi:2011tj].

---


\newpage
\singlespace

# References

